/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantalla1;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author Taller
 */
public class Login extends javax.swing.JFrame {
    int xMouse, yMouse;
    
        
    public Login() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        City = new javax.swing.JLabel();
        inisio = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        CONTRASEÑA = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        CONTRASEÑA1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        eNTRAR1 = new javax.swing.JPanel();
        ENTRAR1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        eNTRAR2 = new javax.swing.JPanel();
        ENTRAR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(204, 204, 204));
        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.setFocusable(false);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantalla1/Imagenes/Logo impretec.png"))); // NOI18N
        bg.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 170, 160));

        City.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantalla1/Imagenes/city.png"))); // NOI18N
        bg.add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 290, 500));

        inisio.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        inisio.setText("INICIAR SESIÓN");
        inisio.setToolTipText("");
        bg.add(inisio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 250, 40));

        usuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        usuario.setText("Usuario");
        bg.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 250, 10));

        CONTRASEÑA.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        CONTRASEÑA.setText("Contraseña");
        CONTRASEÑA.setName(""); // NOI18N
        bg.add(CONTRASEÑA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 250, -1));

        CONTRASEÑA1.setForeground(new java.awt.Color(204, 204, 204));
        CONTRASEÑA1.setText("******");
        CONTRASEÑA1.setBorder(null);
        CONTRASEÑA1.setCaretColor(new java.awt.Color(204, 204, 204));
        CONTRASEÑA1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CONTRASEÑA1.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        CONTRASEÑA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CONTRASEÑA1MousePressed(evt);
            }
        });
        bg.add(CONTRASEÑA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 190, -1));

        jTextField1.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Ingrese su nombre de usuario");
        jTextField1.setBorder(null);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField1MousePressed(evt);
            }
        });
        bg.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 240, -1));

        eNTRAR1.setBackground(new java.awt.Color(0, 74, 173));
        eNTRAR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eNTRAR1MouseClicked(evt);
            }
        });

        ENTRAR1.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        ENTRAR1.setForeground(new java.awt.Color(255, 255, 255));
        ENTRAR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ENTRAR1.setText("REGISTRO");
        ENTRAR1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ENTRAR1.setVerifyInputWhenFocusTarget(false);
        ENTRAR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ENTRAR1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout eNTRAR1Layout = new javax.swing.GroupLayout(eNTRAR1);
        eNTRAR1.setLayout(eNTRAR1Layout);
        eNTRAR1Layout.setHorizontalGroup(
            eNTRAR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eNTRAR1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ENTRAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eNTRAR1Layout.setVerticalGroup(
            eNTRAR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eNTRAR1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ENTRAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(eNTRAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 120, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 748, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 30));

        eNTRAR2.setBackground(new java.awt.Color(0, 74, 173));

        ENTRAR.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        ENTRAR.setForeground(new java.awt.Color(255, 255, 255));
        ENTRAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ENTRAR.setText("ENTRAR");
        ENTRAR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ENTRAR.setVerifyInputWhenFocusTarget(false);
        ENTRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ENTRARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout eNTRAR2Layout = new javax.swing.GroupLayout(eNTRAR2);
        eNTRAR2.setLayout(eNTRAR2Layout);
        eNTRAR2Layout.setHorizontalGroup(
            eNTRAR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eNTRAR2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ENTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        eNTRAR2Layout.setVerticalGroup(
            eNTRAR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eNTRAR2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ENTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(eNTRAR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed

       xMouse = evt.getX();
       yMouse = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MousePressed
        if (jTextField1.getText().isEmpty()) {
        jTextField1.setText("Ingrese su nombre de usuario");
        jTextField1.setForeground(Color.GRAY);
    }
    jTextField1.setText(" ");
    jTextField1.setForeground(Color.BLACK);
    CONTRASEÑA1.setText("*******");
    CONTRASEÑA1.setForeground(Color.GRAY);
                                                               
    }//GEN-LAST:event_jTextField1MousePressed

    private void CONTRASEÑA1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONTRASEÑA1MousePressed
       if (CONTRASEÑA1.getText().isEmpty()) {
        CONTRASEÑA1.setText("Ingrese su contraseña");
        CONTRASEÑA1.setForeground(Color.GRAY);
    }
    // No establecer el texto del jTextField1 en blanco aquí
    CONTRASEÑA1.setText("");
    CONTRASEÑA1.setForeground(Color.BLACK);
    }//GEN-LAST:event_CONTRASEÑA1MousePressed

    private void ENTRAR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENTRAR1MouseClicked
// Abre una nueva ventana de registro
    RegistroForm registroForm = new RegistroForm();
    registroForm.setVisible(true);
    }//GEN-LAST:event_ENTRAR1MouseClicked

    private void ENTRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENTRARMouseClicked
         Pantalla2 pantalla2 = new Pantalla2();
    pantalla2.setVisible(true);
    }//GEN-LAST:event_ENTRARMouseClicked

    private void eNTRAR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eNTRAR1MouseClicked
       
    }//GEN-LAST:event_eNTRAR1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         // Crear una instancia del formulario de espera
     try {
        // Configurar el aspecto y la sensación del UI
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    
    // Crear una instancia del formulario de espera
    PantallaEspera pantallaEspera = new PantallaEspera();
    // Mostrar el formulario de espera
    pantallaEspera.setVisible(true);
    
    // Simular una espera (puedes reemplazar esto con tu lógica real)
    try {
        Thread.sleep(1000); // Esperar 3 segundos (6000 milisegundos)
    } catch (InterruptedException ex) {
        // Manejar la interrupción
    }

    // Cerrar el formulario de espera
    pantallaEspera.dispose();

    // Crear e iniciar la ventana de inicio de sesión
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Login().setVisible(true);
        }
    });
}
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CONTRASEÑA;
    private javax.swing.JPasswordField CONTRASEÑA1;
    private javax.swing.JLabel City;
    private javax.swing.JLabel ENTRAR;
    private javax.swing.JLabel ENTRAR1;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel eNTRAR1;
    private javax.swing.JPanel eNTRAR2;
    private javax.swing.JLabel inisio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
