/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantalla1;

import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DatosGN.Datos_usuario;
import DatosGN.servicio;
import Milogica.ServiciosController;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Taller
 */
public class NuevoServicio extends javax.swing.JFrame {

    int xMouse, yMouse;
    String ruta;

    public NuevoServicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        inisio = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        CONTRASEÑA = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        CONTRASEÑA1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usuario1 = new javax.swing.JLabel();
        NombreServicio = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        usuario3 = new javax.swing.JLabel();
        JCosto = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        LblImagen = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(204, 204, 204));
        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.setFocusable(false);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inisio.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        inisio.setForeground(new java.awt.Color(102, 153, 255));
        inisio.setText("REGISTRO");
        inisio.setToolTipText("");
        bg.add(inisio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        usuario.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        usuario.setText("Nuevo servicio");
        bg.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 204));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 250, 10));

        CONTRASEÑA.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        CONTRASEÑA.setText("Contraseña");
        CONTRASEÑA.setName(""); // NOI18N
        bg.add(CONTRASEÑA, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 250, -1));

        CONTRASEÑA1.setForeground(new java.awt.Color(204, 204, 204));
        CONTRASEÑA1.setText("******");
        CONTRASEÑA1.setBorder(null);
        CONTRASEÑA1.setCaretColor(new java.awt.Color(204, 204, 204));
        CONTRASEÑA1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CONTRASEÑA1.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        CONTRASEÑA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CONTRASEÑA1MousePressed(evt);
            }
        });
        bg.add(CONTRASEÑA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 190, 10));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 748, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantalla1/Imagenes/Imagen de WhatsApp 2024-04-02 a las 12.21.20_9c6b1ea1.jpg"))); // NOI18N
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        usuario1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        usuario1.setText("Descripcion o nombre del servicio");
        bg.add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        NombreServicio.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        NombreServicio.setForeground(new java.awt.Color(204, 204, 204));
        NombreServicio.setText("Nombre del servicio");
        NombreServicio.setBorder(null);
        NombreServicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NombreServicioFocusGained(evt);
            }
        });
        NombreServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NombreServicioMousePressed(evt);
            }
        });
        NombreServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreServicioActionPerformed(evt);
            }
        });
        NombreServicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreServicioKeyPressed(evt);
            }
        });
        bg.add(NombreServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 240, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 250, 10));

        usuario3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        usuario3.setText("Costo");
        bg.add(usuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 60, -1));

        JCosto.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        JCosto.setForeground(new java.awt.Color(204, 204, 204));
        JCosto.setText("Costo del servicio");
        JCosto.setBorder(null);
        JCosto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JCostoFocusGained(evt);
            }
        });
        JCosto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JCostoMousePressed(evt);
            }
        });
        JCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JCostoKeyPressed(evt);
            }
        });
        bg.add(JCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 240, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 250, 10));

        LblImagen.setText("Seleccionar Icono");
        LblImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblImagenMouseClicked(evt);
            }
        });
        bg.add(LblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 130, 130));

        btnRegistrar.setText("registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        bg.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 160, 60));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(693, 693, 693)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addContainerGap(478, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCostoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCostoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCostoMousePressed

    private void NombreServicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreServicioMousePressed


    }//GEN-LAST:event_NombreServicioMousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged

    }//GEN-LAST:event_jLabel2MouseDragged

    private void CONTRASEÑA1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONTRASEÑA1MousePressed

    }//GEN-LAST:event_CONTRASEÑA1MousePressed

    private void NombreServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreServicioActionPerformed

    private void NombreServicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreServicioFocusGained
        NombreServicio.setText("");
        NombreServicio.setForeground(Color.BLACK);
    }//GEN-LAST:event_NombreServicioFocusGained

    private void NombreServicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreServicioKeyPressed
        // Obtener el código de la tecla presionada
        int key = evt.getKeyCode();

        // Verificar si se presionó la tecla Enter (código 10)
        if (key == java.awt.event.KeyEvent.VK_ENTER) {
            // Pasar al siguiente campo de texto
            NombreServicio.requestFocus();
        }
    }//GEN-LAST:event_NombreServicioKeyPressed

    private void JCostoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JCostoKeyPressed
        // Obtener el código de la tecla presionada
        int key = evt.getKeyCode();

        // Verificar si se presionó la tecla Enter (código 10)
        if (key == java.awt.event.KeyEvent.VK_ENTER) {
            // Pasar al siguiente campo de texto
            JCosto.requestFocus();
        }
    }//GEN-LAST:event_JCostoKeyPressed

    private void JCostoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JCostoFocusGained
        JCosto.setText("");
        JCosto.setForeground(Color.BLACK);
    }//GEN-LAST:event_JCostoFocusGained

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        ServiciosController mControler = new ServiciosController();
        servicio mServicio = new servicio();

        mServicio.setDescripcion(NombreServicio.getText());
        mServicio.setPrecio(Float.parseFloat(JCosto.getText()));
        mServicio.setImgen(ruta);

        if (mControler.Agregar(mServicio)) {
            JOptionPane.showMessageDialog(null, "Servicio guardado correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "Error al guardar el servicio");

        }
        this.dispose();
        

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void LblImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblImagenMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        fileChooser.setFileFilter(extensionFilter);

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            ruta = fileChooser.getSelectedFile().getName();
            Image mImagen = new ImageIcon(fileChooser.getSelectedFile().getAbsolutePath()).getImage();
            ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(LblImagen.getWidth(), LblImagen.getHeight(), 0));
            LblImagen.setIcon(mIcono);
        }
    }//GEN-LAST:event_LblImagenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CONTRASEÑA;
    private javax.swing.JPasswordField CONTRASEÑA1;
    private javax.swing.JTextField JCosto;
    private javax.swing.JLabel LblImagen;
    private javax.swing.JTextField NombreServicio;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel inisio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel usuario1;
    private javax.swing.JLabel usuario3;
    // End of variables declaration//GEN-END:variables
}
