/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantalla1;

/**
 *
 * @author Taller
 */
public class Pantalla2 extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla2
     */
    public Pantalla2() {
     try {
    initComponents(); // Inicializar componentes de la GUI

    inicio p1 = new inicio(); // Crear una instancia de la clase "inicio"
    p1.setSize(580, 457); // Establecer el tamaño del componente "p1"
    p1.setLocation(0, 0); // Establecer la ubicación del componente "p1"

    // Verificar si el contenedor "content" no es nulo
    if (content != null) {
        content.removeAll(); // Eliminar todos los componentes del contenedor "content"
        content.add(p1, java.awt.BorderLayout.CENTER); // Agregar el componente "p1" al centro del contenedor "content"
        content.revalidate(); // Revalidar el contenedor "content"
        content.repaint(); // Repintar el contenedor "content"
    } else {
        // Manejar el caso en que el contenedor "content" sea nulo
        System.err.println("El contenedor 'content' es nulo. No se puede agregar el componente 'p1'.");
    }
} catch (Exception e) {
    // Manejar cualquier excepción que pueda ocurrir durante la ejecución del código
    e.printStackTrace(); // Imprimir la traza de la excepción
}

   

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(580, 457));
        content.setToolTipText("");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 74, 173));

        jButton1.setText("Venta");
        jButton1.setBackground(new java.awt.Color(0, 74, 173));
        jButton1.setBorder(null);
        jButton1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Balance");
        jButton2.setBackground(new java.awt.Color(0, 74, 173));
        jButton2.setBorder(null);
        jButton2.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantalla1/Imagenes/Logo impretec.png"))); // NOI18N

        jButton3.setText("Catalogo");
        jButton3.setBackground(new java.awt.Color(0, 74, 173));
        jButton3.setBorder(null);
        jButton3.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantalla1/Imagenes/merma-removebg-preview (2).png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantalla1/Imagenes/usuario.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(529, 529, 529)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 530));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("CONSULTAR");
        jMenu1.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        jMenu4.setText("Venta diaria");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu4);

        jMenu5.setText("Total de copias monocromáticas");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu5);

        jMenu7.setText("Total copias a color");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu7);

        jMenu11.setText("Total impresiones monocromáticas");
        jMenu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu11MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu11);

        jMenu19.setText("Total de Impresiones a color");
        jMenu19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu19MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu19);

        jMenu21.setText("Total merma");
        jMenu21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu21MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu21);

        jMenu23.setText("Total de hojas gastadas");
        jMenu23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu23MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu23);

        jMenu25.setText("Total de engargolados");
        jMenu25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu25MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu25);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
            Panusuario nuevaVentana = new Panusuario();
    
    // Configurar la nueva ventana
    nuevaVentana.setSize(300, 200);
    nuevaVentana.setLocationRelativeTo(null);
    nuevaVentana.setDefaultCloseOperation(Pantalla2.DISPOSE_ON_CLOSE); // Esto asegura que solo se cierre la nueva ventana al hacer clic en su botón de cerrar
    
    // Hacer visible la nueva ventana
    nuevaVentana.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    
    BalPan p2 = new BalPan(); // Crear una instancia de la clase "inicio"
    p2.setSize(580, 457); // Establecer el tamaño del componente "p1"
    p2.setLocation(0, 0); // Establecer la ubicación del componente "p1"

    // Verificar si el contenedor "content" no es nulo

        content.removeAll(); // Eliminar todos los componentes del contenedor "content"
        content.add(p2, java.awt.BorderLayout.CENTER);
        content.revalidate();// Agregar el componente "p1" al centro del contenedor "content"
        content.repaint();
    

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    inicio p1 = new inicio(); // Crear una instancia de la clase "inicio"
    p1.setSize(580, 457); // Establecer el tamaño del componente "p1"
    p1.setLocation(0, 0); // Establecer la ubicación del componente "p1"

    // Verificar si el contenedor "content" no es nulo

        content.removeAll(); // Eliminar todos los componentes del contenedor "content"
        content.add(p1, java.awt.BorderLayout.CENTER);
        content.revalidate();// Agregar el componente "p1" al centro del contenedor "content"
        content.repaint();
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         PanCat p3 = new PanCat(); //ear una instancia de la clase "inicio"
    p3.setSize(580, 457); // Establecer el tamaño del componente "p1"
    p3.setLocation(0, 0); // Establecer la ubicación del componente "p1"

    // Verificar si el contenedor "content" no es nulo

        content.removeAll(); // Eliminar todos los componentes del contenedor "content"
        content.add(p3, java.awt.BorderLayout.CENTER);
        content.revalidate();// Agregar el componente "p1" al centro del contenedor "content"
        content.repaint();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
         Merma nuevaInterfaz = new Merma();
    nuevaInterfaz.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
    
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        VentaDiaria p4 = new VentaDiaria(); //ear una instancia de la clase "inicio"
    p4.setSize(580, 457); // Establecer el tamaño del componente "p1"
    p4.setLocation(0, 0); // Establecer la ubicación del componente "p1"

    // Verificar si el contenedor "content" no es nulo

        content.removeAll(); // Eliminar todos los componentes del contenedor "content"
        content.add(p4, java.awt.BorderLayout.CENTER);
        content.revalidate();// Agregar el componente "p1" al centro del contenedor "content"
        content.repaint();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
       TotalcopM p5 = new TotalcopM(); //ear una instancia de la clase "inicio"
    p5.setSize(580, 457); // Establecer el tamaño del componente "p1"
    p5.setLocation(0, 0); // Establecer la ubicación del componente "p1"

    // Verificar si el contenedor "content" no es nulo

        content.removeAll(); // Eliminar todos los componentes del contenedor "content"
        content.add(p5, java.awt.BorderLayout.CENTER);
        content.revalidate();// Agregar el componente "p1" al centro del contenedor "content"
        content.repaint();
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        Ccolo p6 = new Ccolo(); //ear una instancia de la clase "inicio"
    p6.setSize(580, 457); // Establecer el tamaño del componente "p1"
    p6.setLocation(0, 0); // Establecer la ubicación del componente "p1"

    // Verificar si el contenedor "content" no es nulo

        content.removeAll(); // Eliminar todos los componentes del contenedor "content"
        content.add(p6, java.awt.BorderLayout.CENTER);
        content.revalidate();// Agregar el componente "p1" al centro del contenedor "content"
        content.repaint();
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenu11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu11MouseClicked
        toimmono p7 = new toimmono(); //ear una instancia de la clase "inicio"
    p7.setSize(580, 457); // Establecer el tamaño del componente "p1"
    p7.setLocation(0, 0); // Establecer la ubicación del componente "p1"

    // Verificar si el contenedor "content" no es nulo

        content.removeAll(); // Eliminar todos los componentes del contenedor "content"
        content.add(p7, java.awt.BorderLayout.CENTER);
        content.revalidate();// Agregar el componente "p1" al centro del contenedor "content"
        content.repaint();
    }//GEN-LAST:event_jMenu11MouseClicked

    private void jMenu19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu19MouseClicked
        Toimco p8 = new Toimco(); //ear una instancia de la clase "inicio"
    p8.setSize(580, 457); // Establecer el tamaño del componente "p1"
    p8.setLocation(0, 0); // Establecer la ubicación del componente "p1"

    // Verificar si el contenedor "content" no es nulo

        content.removeAll(); // Eliminar todos los componentes del contenedor "content"
        content.add(p8, java.awt.BorderLayout.CENTER);
        content.revalidate();// Agregar el componente "p1" al centro del contenedor "content"
        content.repaint();
    }//GEN-LAST:event_jMenu19MouseClicked

    private void jMenu21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu21MouseClicked
       totalmerma p9 = new totalmerma(); //ear una instancia de la clase "inicio"
    p9.setSize(580, 457); // Establecer el tamaño del componente "p1"
    p9.setLocation(0, 0); // Establecer la ubicación del componente "p1"

    // Verificar si el contenedor "content" no es nulo

        content.removeAll(); // Eliminar todos los componentes del contenedor "content"
        content.add(p9, java.awt.BorderLayout.CENTER);
        content.revalidate();// Agregar el componente "p1" al centro del contenedor "content"
        content.repaint();
    }//GEN-LAST:event_jMenu21MouseClicked

    private void jMenu23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu23MouseClicked
        TotalHoGas p10 = new TotalHoGas(); //ear una instancia de la clase "inicio"
    p10.setSize(580, 457); // Establecer el tamaño del componente "p1"
    p10.setLocation(0, 0); // Establecer la ubicación del componente "p1"

    // Verificar si el contenedor "content" no es nulo

        content.removeAll(); // Eliminar todos los componentes del contenedor "content"
        content.add(p10, java.awt.BorderLayout.CENTER);
        content.revalidate();// Agregar el componente "p1" al centro del contenedor "content"
        content.repaint();
    }//GEN-LAST:event_jMenu23MouseClicked

    private void jMenu25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu25MouseClicked
        toenngargolados p11 = new toenngargolados(); //ear una instancia de la clase "inicio"
    p11.setSize(580, 457); // Establecer el tamaño del componente "p1"
    p11.setLocation(0, 0); // Establecer la ubicación del componente "p1"

    // Verificar si el contenedor "content" no es nulo

        content.removeAll(); // Eliminar todos los componentes del contenedor "content"
        content.add(p11, java.awt.BorderLayout.CENTER);
        content.revalidate();// Agregar el componente "p1" al centro del contenedor "content"
        content.repaint();
    }//GEN-LAST:event_jMenu25MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
